export const randomWords = [
  // Web App & SaaS
  "dashboard",
  "analytics tool",
  "CRM system",
  "project management app",
  "task tracker",
  "note-taking app",
  "time tracking tool",
  "calendar integration",
  "finance tracker",
  "subscription billing app",
  "recruitment platform",
  "inventory management system",
  "customer support app",
  "internal tool",
  "marketing dashboard",
  "team collaboration app",
  "AI writing assistant",
  "code documentation site",
  "developer tool",
  "workflow automation",

  // E-commerce
  "e-commerce store",
  "product landing page",
  "checkout flow",
  "pricing page",
  "shopping cart UI",
  "product comparison site",
  "digital downloads store",
  "niche marketplace",
  "product review blog",
  "fashion catalog",

  // Education
  "online course platform",
  "student dashboard",
  "tutor booking app",
  "bootcamp landing page",
  "webinar page",
  "e-learning app",
  "knowledge base",
  "interactive quiz UI",
  "certification dashboard",

  // Social
  "forum interface",
  "community dashboard",
  "messaging app UI",
  "profile page",
  "feed UI",
  "live stream page",
  "creator portfolio",
  "social bio link page",
  "fan club site",

  // Business
  "agency landing page",
  "consulting firm site",
  "startup hero section",
  "enterprise pricing page",
  "case study layout",
  "client onboarding UI",
  "B2B platform",
  "HR tool",

  // Creative
  "portfolio gallery",
  "photographer site",
  "music artist profile",
  "designer resume page",
  "personal blog layout",
  "writers homepage",
  "art showcase",
  "creative studio page",
  "podcast site",

  // Utility
  "restaurant site",
  "travel booking UI",
  "fitness tracker",
  "finance app",
  "healthcare dashboard",
  "non-profit donation page",
  "event RSVP page",
  "real estate listings",
  "weather app UI",
];
